name: Cruelty
description: Rid of players using non-standard methods.
author: Wolflink289

version: 1.0.0
main: com.wolflink289.bukkit.cruelty.CrueltyPlugin

depend: [ProtocolLib]

commands:
    crueldos:
        description: Initiate a fake DoS attack on a one or more players.
        usage: Unimplemented
        aliases: [cdos]
        permission: cruelty.attack.dos
        permission-message: Unknown command. Type "help" for help.
    cruelcrash:
        description: Crash one or more players' clients.
        usage: /cruelcrash [Player,Player]
        aliases: [ccrash, cc]
        permission: cruelty.attack.crash
        permission-message: Unknown command. Type "help" for help.
    cruelfeign:
        description: Fake one or more players' deaths.
        usage: /cruelfeign [Player,Player]
        aliases: [cfeign, cfe]
        permission: cruelty.attack.feign
        permission-message: Unknown command. Type "help" for help.
    cruelfreeze:
        description: Freeze one or more players' clients.
        usage: /cruelfreeze [Player,Player]
        aliases: [cfreeze, cfr]
        permission: cruelty.attack.freeze
        permission-message: Unknown command. Type "help" for help.
    cruelinventoryfuck:
        description: Fuck with one or more players' inventories.
        usage: /cruelinventoryfuck [Player,Player] [Method]
        aliases: [cif, cifuck, cinvfuck, cruelifuck, cruelinvfuck]
        permission: cruelty.attack.invfuck
        permission-message: Unknown command. Type "help" for help.
    cruelspam:
        description: Spam one or more players' chats.
        usage: /cruelspam [Player,Player] [Method]
        aliases: [cs, cspam]
        permission: cruelty.attack.spam
        permission-message: Unknown command. Type "help" for help.
    
permissions:
    cruelty.*:
        description: Gives access to all Cruelty features and protections.
        default: op
        children:
            cruelty.attack.*: true
            cruelty.immune.*: true
    cruelty.attack.*:
        description: Gives access to all Cruelty "attack" features.
        default: op
        children:
            cruelty.attack.dos: true
            cruelty.attack.crash: true
            cruelty.attack.feign: true
            cruelty.attack.freeze: true
            cruelty.attack.invfuck: true
            cruelty.attack.spam: true
    cruelty.attack.dos:
        description: Allows the user to initiate a fake DoS attack on a player.
        default: op
    cruelty.attack.crash:
        description: Allows the user to crash a player.
        default: op
    cruelty.attack.feign:
        description: Allows the user to fake a player's death.
        default: op
    cruelty.attack.freeze:
        description: Allows the user to freeze a player's client.
        default: op
    cruelty.attack.invfuck:
        description: Allows the user to fuck with a player's inventory.
        default: op
    cruelty.attack.spam:
        description: Allows the user to spam a player's chat with fake bots.
        default: op
    cruelty.immune.*:
        description: Gives access to all Cruelty immunities.
        default: op
        children:
            cruelty.immune.dos: true
            cruelty.immune.crash: true
            cruelty.immune.feign: true
            cruelty.immune.freeze: true
            cruelty.immune.invfuck: true
    cruelty.immune.dos:
        description: The user becomes immune to the DoS attack.
        default: op
    cruelty.immune.crash:
        description: The user becomes immune to the crash attack.
        default: op
    cruelty.immune.feign:
        description: The user becomes immune to the feign attack.
        default: op
    cruelty.immune.freeze:
        description: The user becomes immune to the freeze attack.
        default: op
    cruelty.immune.invfuck:
        description: The user becomes immune to having their inventory fucked with.
        default: op
    cruelty.immune.spam:
        description: The user becomes immune to having their chat fake-spammed.
        default: op